image: java:8-jdk

stages:
  - build
  - test
  - deploy

before_script:
#  - echo `pwd` # debug
#  - echo "$CI_BUILD_NAME, $CI_BUILD_REF_NAME $CI_BUILD_STAGE" # debug
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - chmod +x gradlew

build:
  stage: build

  script:
    - ./gradlew build
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week
  only:
    - master

test:
  stage: test
  script:
    - ./gradlew check
  artifacts:      
    reports:   
      junit: build/test-results/test/TEST-*.xml

  stage: coverage
  script:
    - ./gradlew jacocoTestReport
  artifacts:    
    paths:     
      - build/reports/jacoco/test/html


after_script:
  - echo "End CI"